// Generated by gencpp from file natnet_ros_cpp/MarkerPosesRequest.msg
// DO NOT EDIT!


#ifndef NATNET_ROS_CPP_MESSAGE_MARKERPOSESREQUEST_H
#define NATNET_ROS_CPP_MESSAGE_MARKERPOSESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace natnet_ros_cpp
{
template <class ContainerAllocator>
struct MarkerPosesRequest_
{
  typedef MarkerPosesRequest_<ContainerAllocator> Type;

  MarkerPosesRequest_()
    {
    }
  MarkerPosesRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::natnet_ros_cpp::MarkerPosesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::natnet_ros_cpp::MarkerPosesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MarkerPosesRequest_

typedef ::natnet_ros_cpp::MarkerPosesRequest_<std::allocator<void> > MarkerPosesRequest;

typedef boost::shared_ptr< ::natnet_ros_cpp::MarkerPosesRequest > MarkerPosesRequestPtr;
typedef boost::shared_ptr< ::natnet_ros_cpp::MarkerPosesRequest const> MarkerPosesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::natnet_ros_cpp::MarkerPosesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::natnet_ros_cpp::MarkerPosesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace natnet_ros_cpp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::natnet_ros_cpp::MarkerPosesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::natnet_ros_cpp::MarkerPosesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::natnet_ros_cpp::MarkerPosesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::natnet_ros_cpp::MarkerPosesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::natnet_ros_cpp::MarkerPosesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::natnet_ros_cpp::MarkerPosesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::natnet_ros_cpp::MarkerPosesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::natnet_ros_cpp::MarkerPosesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::natnet_ros_cpp::MarkerPosesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "natnet_ros_cpp/MarkerPosesRequest";
  }

  static const char* value(const ::natnet_ros_cpp::MarkerPosesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::natnet_ros_cpp::MarkerPosesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::natnet_ros_cpp::MarkerPosesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::natnet_ros_cpp::MarkerPosesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MarkerPosesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::natnet_ros_cpp::MarkerPosesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::natnet_ros_cpp::MarkerPosesRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // NATNET_ROS_CPP_MESSAGE_MARKERPOSESREQUEST_H
